title: TAG
description: Teaching-Focused Faculty Advocacy Group at Smith College
theme: just-the-docs
logo: "/assets/images/TAG_pixels.png"
url: https://just-the-docs.github.io
favicon_ico: "/assets/images/favicon.ico"

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
